//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Руль_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compazition
    {
        public int ID_Compazition { get; set; }
        public Nullable<int> ID_Order { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public string Name { get; set; }
        public string Discription { get; set; }
        public string Maker { get; set; }
        public string Image { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Max_Discount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
