//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Руль_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Compazition = new HashSet<Compazition>();
        }
    
        public int ID_Order { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> ID_Client { get; set; }
        public Nullable<int> Cont { get; set; }
        public Nullable<int> ID_Extradition { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compazition> Compazition { get; set; }
        public virtual Point_Extradition Point_Extradition { get; set; }
        public virtual Product Product { get; set; }
    }
}
