//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО__Руль_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID_Staff { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual User User { get; set; }
    }
}
